---
galaxy_info:
  author: Naza
  description: Install and configure Cloud Torrent web-based torrent client
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: Fedora
      versions:
        - all

  galaxy_tags:
    - torrent
    - bittorrent
    - cloud
    - web
    - downloads
    - media

dependencies: []

collections:
  - ansible.posix
  - community.general
