---
# Configure Immich pod. All env vars are inlined into the pod YAML below, so no
# separate env file is generated.

- name: Generate Kubernetes YAML pod definition
  ansible.builtin.template:
    src: immich-pod.yaml.j2
    dest: "{{ immich_config_dir }}/immich-pod.yaml"
    owner: "{{ immich_user }}"
    group: "{{ immich_group }}"
    mode: '0644'
  become: true
  notify: container restart
