---
# Variables por defecto del role Cockpit

cockpit_packages:
  - cockpit
  - cockpit-networkmanager
  - cockpit-packagekit
  - cockpit-selinux
  - cockpit-storaged
  - cockpit-system
  - cockpit-files
  - cockpit-podman

cockpit_podman_packages:
  - podman
  - podman-compose
  - slirp4netns  # Requerido para el networking de containers rootless

cockpit_service_name: cockpit.socket
cockpit_service_enabled: true
cockpit_service_state: started

cockpit_podman_enable_socket: true

# Bindeado a 127.0.0.1; expuesto solo vía el vhost 443 de NGINX.
cockpit_port: 9090
