---
- name: Install SELinux policy packages
  ansible.builtin.dnf:
    name:
      - policycoreutils-python-utils
    state: present
  become: true
  when: ansible_facts['selinux'].mode | default('') == 'enforcing'

- name: Set SELinux file contexts for FileBrowser
  community.general.sefcontext:
    target: "{{ item.target }}"
    setype: "{{ item.setype }}"
    state: present
  become: true
  loop:
    - { target: "{{ filebrowser_install_dir }}/filebrowser", setype: bin_t }
    - { target: "{{ filebrowser_working_dir }}(/.*)?", setype: var_lib_t }
    - { target: "{{ filebrowser_root_dir }}(/.*)?", setype: public_content_rw_t }
  loop_control:
    label: "{{ item.target }}"
  when: ansible_facts['selinux'].mode | default('') == 'enforcing'
  notify: Filebrowser apply selinux context

- name: Allow FileBrowser to bind to custom port
  community.general.seport:
    ports: "{{ filebrowser_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  become: true
  when:
    - ansible_facts['selinux'].mode | default('') == 'enforcing'
    - filebrowser_port != 80 and filebrowser_port != 443
