---
# Handlers del role Cockpit

- name: Restart cockpit
  ansible.builtin.systemd:
    name: cockpit.service
    state: restarted
  become: true

- name: Restart cockpit socket
  ansible.builtin.systemd:
    name: cockpit.socket
    state: restarted
    daemon_reload: true
  become: true
