---
# Handlers for Jellyfin role

- name: daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: restart jellyfin
  ansible.builtin.systemd:
    name: "{{ jellyfin_service_name }}"
    state: restarted
  become: true

- name: jellyfin apply selinux context
  ansible.builtin.command: "restorecon -Rv {{ item }}"
  become: true
  changed_when: false
  loop:
    - "{{ jellyfin_data_dir }}"
    - "{{ jellyfin_config_dir }}"
    - "{{ jellyfin_cache_dir }}"
    - "{{ jellyfin_log_dir }}"
    - "{{ jellyfin_media_dir }}"
